
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/myspm/hellospm
	@mkdir  ../../sea-modules/myspm/hellospm
	@mkdir  ../../sea-modules/myspm/hellospm/1.0.0
	@cp     dist/*.* ../../sea-modules/myspm/hellospm/1.0.0
	@echo
	@echo   " deploy to seajs-modules/myspm/hellospm/1.0.0"
	@echo
